# Teleop configuration for Standard joystick.
joystick_teleop:
  teleop_twist_joy:
    axis_linear: 1
    scale_linear: 0.5
    scale_linear_turbo: 1.0
    axis_angular: 0
    scale_angular: 4.0
    enable_button: 5
    enable_turbo_button: 7
  joy_node:
    deadzone: 0.05
    autorepeat_rate: 20
